// scripts/gen-skills.mts — inline the shipped skill pack into a TS module.
//
// Run via the `gen:skills` package script, and re-run it after editing anything in
// `skills/mocktown/`. `tests/skills.test.ts` fails when the two disagree, so a forgotten
// run is caught by `bun run test` rather than shipping a pack that is a version behind.
//
// Why this exists at all: the pack lives at the **repo root** because that is the layout
// the skills ecosystem discovers (`npx skills add gkurt/mocktown` installs it straight
// from GitHub, with no checkout and no mocktown install). But a `with { type: 'text' }`
// specifier pointing there leaves `packages/mocktown`, and npm cannot carry a path outside
// the package into the tarball — a published install would resolve it against the
// *consumer's* root, find nothing, and throw while the daemon was still importing modules.
// Generating a package-local module keeps the root layout and makes the tarball
// self-contained, with one editable copy of every file.

import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const packDir = join(root, 'skills', 'mocktown');
const out = join(root, 'packages', 'mocktown', 'src', 'skills', 'pack.gen.ts');

/** Sorted, so an unrelated edit never reorders the file and shows up as a diff. */
export function readPack(): Record<string, string> {
  const files = readdirSync(packDir)
    .filter((name) => name.endsWith('.md'))
    .sort();
  if (!files.includes('SKILL.md')) throw new Error(`${packDir} has no SKILL.md — that is the file every agent host reads first`);
  return Object.fromEntries(files.map((name) => [name, readFileSync(join(packDir, name), 'utf8')]));
}

/**
 * `JSON.stringify` per value rather than a template literal: the pack is markdown about
 * writing code, so it is full of backticks and `${`, and a literal would need escaping
 * rules that silently corrupt the text the day one is missed.
 */
export function render(pack: Record<string, string>): string {
  const entries = Object.entries(pack)
    .map(([name, text]) => `  ${JSON.stringify(name)}: ${JSON.stringify(text)},`)
    .join('\n');
  return `// Generated by scripts/gen-skills.mts from skills/mocktown/ — do not edit.
// Run \`bun run gen:skills\` after changing the pack.

/** Every file in the shipped pack, keyed by its path relative to the skill directory. */
export const PACK_FILES: Record<string, string> = {
${entries}
};
`;
}

const pack = readPack();
writeFileSync(out, render(pack));
console.log(`wrote ${out} — ${Object.keys(pack).length} files`);
