/**
 * `.mocktown/.gitignore` — the directory deciding for itself what of it is committed.
 *
 * `.mocktown/` holds two kinds of thing that happen to share a parent. Some of it is
 * derived: issues mirrored from the database, the generated JSON Schema, machine-local
 * config. The mocks and the panels are the opposite — hand-authored, the reason the
 * project has a mock at all, and worth having on the next machine that clones this.
 *
 * Putting the rule here rather than in the repo's own `.gitignore` keeps mocktown out of
 * a file that belongs to the project, and it is the only form that works: git does not
 * descend into an ignored directory, so a repo-level `.mocktown/` makes any later
 * `!.mocktown/mocks/` unreachable. Anchoring with `/*` matters for the same class of
 * reason — a bare `*` matches at every depth and would ignore the mock files again after
 * their directory was let back in.
 */
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, relative, sep } from 'node:path';

const HEADER = [
  '# Generated by mocktown. Everything in .mocktown/ is local, derived state — except the',
  '# mocks and the panels, which are hand-authored and committed.',
  '#',
  '# `/*` is anchored on purpose: a bare `*` matches at every depth and would ignore the',
  '# files inside a directory this file just let back in.',
];

/**
 * Which of the committed directories are direct children of `.mocktown/`. One pointed
 * somewhere else is not this file's business — it is outside, and whatever ignores the
 * repo root applies to it.
 */
function committedChildren(localDir: string, committed: string[]): string[] {
  const names = committed.map((dir) => relative(localDir, dir)).filter((rel) => rel && !rel.startsWith('..') && !rel.includes(sep));
  return [...new Set(names)].sort();
}

export function renderLocalIgnore(localDir: string, committed: string[]): string {
  const keep = committedChildren(localDir, committed);
  return [...HEADER, '/*', '!/.gitignore', ...keep.map((name) => `!/${name}/`), ''].join('\n');
}

/**
 * Written on init and refreshed whenever it is absent. Never overwritten: someone may have
 * added a line of their own, and this file is theirs once it is in their repo.
 */
export function writeLocalIgnore(localIgnore: string, localDir: string, committed: string[]): boolean {
  if (existsSync(localIgnore)) return false;
  mkdirSync(dirname(localIgnore), { recursive: true });
  writeFileSync(localIgnore, renderLocalIgnore(localDir, committed));
  return true;
}

/** Which committed directories the file on disk fails to name — a moved `dirs` entry needs a new line. */
export function localIgnoreMisses(localIgnore: string, localDir: string, committed: string[]): string[] {
  const keep = committedChildren(localDir, committed);
  if (keep.length === 0) return [];
  if (!existsSync(localIgnore)) return keep;
  const lines = readFileSync(localIgnore, 'utf8').split('\n');
  return keep.filter((name) => !lines.includes(`!/${name}/`));
}
