/**
 * `.mocktown/.gitignore` — the directory deciding for itself what of it is committed.
 *
 * It names the derived files rather than ignoring everything and letting a few back in.
 * mocktown writes three things here it would rather not see in a diff: machine-local
 * config, the JSON Schema for the installed version, and the issue files mirrored out of
 * the database. Everything else — the mocks, the panels, and whatever else someone finds
 * it useful to keep beside them — is theirs and is committed.
 *
 * That direction matters more than it looks. An ignore-everything rule silently swallows
 * anything mocktown has not been taught about, including a file a person put there on
 * purpose, and the loss shows up on someone else's clone rather than on the machine that
 * caused it. Naming what mocktown generates can only ever be wrong about mocktown's own
 * files, which is a mistake this repo can fix.
 *
 * Putting the rule here rather than in the repo's own `.gitignore` also keeps mocktown out
 * of a file that belongs to the project — and it is the only form that works: git does not
 * descend into an ignored directory, so a repo-level `.mocktown/` would make anything
 * underneath it unreachable however the rules here were written.
 */
import { existsSync, mkdirSync, writeFileSync } from 'node:fs';
import { dirname, relative, sep } from 'node:path';

const HEADER = [
  '# Generated by mocktown. These are the files mocktown derives — regenerated on demand,',
  '# or specific to this machine. Everything else in .mocktown/ is committed: the mocks,',
  '# the panels, and anything you keep beside them.',
];

/** Paths that live directly under `.mocktown/`, as the names an ignore rule can use. */
function childrenOf(localDir: string, paths: string[]): string[] {
  const names = paths.map((path) => relative(localDir, path)).filter((rel) => rel && !rel.startsWith('..') && !rel.includes(sep));
  return [...new Set(names)].sort();
}

export function renderLocalIgnore(localDir: string, derivedFiles: string[], derivedDirs: string[]): string {
  return [
    ...HEADER,
    ...childrenOf(localDir, derivedFiles).map((name) => `/${name}`),
    ...childrenOf(localDir, derivedDirs).map((name) => `/${name}/`),
    '',
  ].join('\n');
}

/**
 * Written on init and on the first scaffold. Never overwritten: once this file is in
 * someone's repo it is theirs, and they may well have added a line of their own.
 */
export function writeLocalIgnore(localIgnore: string, localDir: string, derivedFiles: string[], derivedDirs: string[]): boolean {
  if (existsSync(localIgnore)) return false;
  mkdirSync(dirname(localIgnore), { recursive: true });
  writeFileSync(localIgnore, renderLocalIgnore(localDir, derivedFiles, derivedDirs));
  return true;
}
