/**
 * `.mocktown/.gitignore` — the directory deciding for itself what of it is committed.
 *
 * `.mocktown/` holds two kinds of thing that happen to share a parent. Most of it is
 * derived: issues mirrored from the database, the generated JSON Schema, machine-local
 * config. The mocks are the opposite — the agent loop's output, hand-edited, and the
 * reason the project has a mock at all.
 *
 * Putting the rule here rather than in the repo's own `.gitignore` keeps mocktown out of
 * a file that belongs to the project, and it is the only form that works: git does not
 * descend into an ignored directory, so a repo-level `.mocktown/` makes any later
 * `!.mocktown/mocks/` unreachable. Anchoring with `/*` matters for the same class of
 * reason — a bare `*` matches at every depth and would ignore the mock files again after
 * their directory was let back in.
 */
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, relative, sep } from 'node:path';

const HEADER = [
  '# Generated by mocktown. Everything in .mocktown/ is local, derived state — except the',
  '# mocks, which are the committed output of the agent loop.',
  '#',
  '# `/*` is anchored on purpose: a bare `*` matches at every depth and would ignore the',
  '# files inside a directory this file just let back in.',
];

/**
 * Which of the configured directories live inside `.mocktown/` and hold committed work.
 * A `dirs.mocks` pointed somewhere else is not this file's business — it is outside, and
 * whatever ignores the repo root applies to it.
 */
function committedChildren(localDir: string, mocksDir: string): string[] {
  const rel = relative(localDir, mocksDir);
  if (!rel || rel.startsWith('..') || rel.includes(sep)) return [];
  return [rel];
}

export function renderLocalIgnore(localDir: string, mocksDir: string): string {
  const keep = committedChildren(localDir, mocksDir);
  return [...HEADER, '/*', '!/.gitignore', ...keep.map((name) => `!/${name}/`), ''].join('\n');
}

/**
 * Written on init and refreshed whenever it is absent. Never overwritten: someone may have
 * added a line of their own, and this file is theirs once it is in their repo.
 */
export function writeLocalIgnore(localIgnore: string, localDir: string, mocksDir: string): boolean {
  if (existsSync(localIgnore)) return false;
  mkdirSync(dirname(localIgnore), { recursive: true });
  writeFileSync(localIgnore, renderLocalIgnore(localDir, mocksDir));
  return true;
}

/** True when the file on disk still names this mocks directory — a moved `dirs.mocks` needs a new line. */
export function localIgnoreCovers(localIgnore: string, localDir: string, mocksDir: string): boolean {
  const keep = committedChildren(localDir, mocksDir);
  if (keep.length === 0) return true;
  if (!existsSync(localIgnore)) return false;
  const lines = readFileSync(localIgnore, 'utf8').split('\n');
  return keep.every((name) => lines.includes(`!/${name}/`));
}
